#Rename the file to be docker-compose
#docker-compose scale up file
#To execute this docker-compose yml file use docker-compose up -d

#selenium-hub: equivalent to manually running the command docker run -d -p 4444:4444 --name selenium-hub  -P selenium/hub
selenium-hub:
  restart: always
  image: selenium/hub:3.11.0-californium
  ports:
    - 4448:4444
#selenium-chrome equivalent to manually running the command docker run -d --link selenium-hub:hub -P --name chrome selenium/node-chrome-debug
chromenode:
  restart: always
  image: selenium/node-chrome-debug:3.11.0-californium
  environment:
    - NODE_MAX_INSTANCE=5
    - NODE_MAX_SESSION=5
  ports:
    - 5900
  #stdin_open: true
  links:
    - selenium-hub:hub
    
#selenium-firefox equivalent to manually running the command docker run -d --link selenium-hub:hub -P --name firefox selenium/node-firefox-debug
firefoxnode:
  restart: always
  image: selenium/node-firefox-debug:3.11.0-californium
  environment:
    - NODE_MAX_INSTANCE=5
    - NODE_MAX_SESSION=5
  ports:
    - 5900
  links:
    - selenium-hub:hub